FROM ruby:3.4.9

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        nodejs \
        graphviz \
        kakasi \
        libkakasi2-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY Gemfile* ./
RUN bundle install
# COPY . .

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
