default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("RAILS_DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("RAILS_DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: chi_bus_development

test:
  <<: *default
  database: chi_bus_test

production:
  <<: *default
  database: chi_bus_production
