# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c4d4fcf37112c5334ec5caafad534a458b80c64d2d4407a7ba3b6e4fc4b4179c9052d2327c21dfc18a6a786beeaacfe9bc28dd6805b0df421b27438dc89f5cfe
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>

test:
  secret_key_base: 4be3d844bad28f11c234dc61739a3dbeee4292b3bf82519e690007b8b62fb207e5c3bc2837c0af9eba6ef7e036a1cb303030db3473f201bad5a504568e40545a
  google_api_key: abc123

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
